-------------------------------------------------------------------
---------- Formatting the Product Table
SELECT [ProductKey]
      ,[ProductAlternateKey]
      --,[WeightUnitMeasureCode]
      --,[SizeUnitMeasureCode]
      ,[EnglishProductName]
	  , c.EnglishProductCategoryName AS [Category Name]
	  , sc.EnglishProductSubcategoryName AS [SubCategory Name]
      --,[SpanishProductName]
      --,[FrenchProductName]
      --,[StandardCost]
      --,[FinishedGoodsFlag]
      ,[Color]
      --,[SafetyStockLevel]
      --,[ReorderPoint]
      --,[ListPrice]
      ,[Size]
      --,[SizeRange]
      --,[Weight]
      --,[DaysToManufacture]
      ,[ProductLine] AS [Product Line]
      --,[DealerPrice]
      --,[Class]
      --,[Style]
      ,[ModelName] AS [Product Model]
      --,[LargePhoto]
      ,[EnglishDescription]
      --,[FrenchDescription]
      --,[ChineseDescription]
      --,[ArabicDescription]
      --,[HebrewDescription]
      --,[ThaiDescription]
      --,[GermanDescription]
      --,[JapaneseDescription]
      --,[TurkishDescription]
      --,[StartDate]
      --,[EndDate]
      ,ISNULL([Status], 'Outdated') AS [Status]
FROM [AdventureWorksDW2022].[dbo].[DimProduct] AS p
LEFT JOIN AdventureWorksDW2022.dbo.DimProductSubcategory AS sc ON p.ProductSubcategoryKey = sc.ProductSubcategoryKey
LEFT JOIN AdventureWorksDW2022.dbo.DimProductCategory AS c ON c.ProductCategoryKey = sc.ProductCategoryKey
ORDER BY p.ProductKey